// 纯香水数据。与 STag ID 无关；ID 归属在 id_mapping.js。
export const CATALOG = {
  "nocturne-cedar": {
    name: "NOCTURNE CEDAR 02",
    house: "Maison Interface",
    family: "Woody Amber",
    concentration: "Eau de Parfum",
    price: "$168 / 75 ml",
    accent: "#38d9b3",
    hero: "Dry cedar, mineral amber, and a quiet smoke trail.",
    notes: {
      top: ["Bergamot peel", "Pink pepper", "Cold cardamom"],
      heart: ["Cedar leaf", "Iris root", "Mineral accord"],
      base: ["Virginia cedar", "Amber resin", "Soft smoke"],
    },
    accords: [
      { name: "Woody", value: 92 },
      { name: "Amber", value: 72 },
      { name: "Smoke", value: 44 },
      { name: "Fresh", value: 34 },
    ],
  },
  "citrus-rain": {
    name: "CITRUS RAIN 11",
    house: "Maison Interface",
    family: "Fresh Citrus",
    concentration: "Eau de Toilette",
    price: "$128 / 100 ml",
    accent: "#7ee35d",
    hero: "Green mandarin, wet basil, and sun-warmed white musk.",
    notes: {
      top: ["Mandarin", "Lime zest", "Rain accord"],
      heart: ["Basil", "Neroli", "Green tea"],
      base: ["White musk", "Vetiver mist", "Cedar water"],
    },
    accords: [
      { name: "Citrus", value: 96 },
      { name: "Green", value: 80 },
      { name: "Aquatic", value: 58 },
      { name: "Musk", value: 42 },
    ],
  },
  "rose-archive": {
    name: "ROSE ARCHIVE 19",
    house: "Maison Interface",
    family: "Floral Musk",
    concentration: "Eau de Parfum",
    price: "$156 / 75 ml",
    accent: "#ff6f91",
    hero: "A modern rose with pear skin, clean musk, and a lacquered petal shine.",
    notes: {
      top: ["Pear skin", "Lychee", "Sparkling aldehyde"],
      heart: ["Damask rose", "Peony", "Violet leaf"],
      base: ["Clean musk", "Cashmere wood", "Pink pepper"],
    },
    accords: [
      { name: "Rose", value: 90 },
      { name: "Musk", value: 70 },
      { name: "Fruity", value: 48 },
      { name: "Powder", value: 38 },
    ],
  },
  "amber-smoke": {
    name: "AMBER SMOKE 27",
    house: "Maison Interface",
    family: "Gourmand Resin",
    concentration: "Parfum",
    price: "$210 / 50 ml",
    accent: "#ffba55",
    hero: "Vanilla resin, dark tonka, and a polished ember finish.",
    notes: {
      top: ["Saffron", "Black pepper", "Orange bitter"],
      heart: ["Labdanum", "Tonka bean", "Burnished vanilla"],
      base: ["Amber resin", "Guaiac wood", "Smoked sugar"],
    },
    accords: [
      { name: "Amber", value: 94 },
      { name: "Sweet", value: 72 },
      { name: "Smoke", value: 62 },
      { name: "Spice", value: 48 },
    ],
  },
  "iris-signal": {
    name: "IRIS SIGNAL 33",
    house: "Maison Interface",
    family: "Powdery Floral",
    concentration: "Eau de Parfum",
    price: "$182 / 75 ml",
    accent: "#bda8ff",
    hero: "Cool iris, violet air, and a polished cosmetic-powder finish.",
    notes: {
      top: ["Violet leaf", "Aldehydes", "Lemon mist"],
      heart: ["Iris butter", "Orris root", "White suede"],
      base: ["Musk", "Cedar pencil", "Rice powder"],
    },
    accords: [
      { name: "Powder", value: 88 },
      { name: "Iris", value: 82 },
      { name: "Musk", value: 54 },
      { name: "Woody", value: 38 },
    ],
  },
};
